name = "sp-cms-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "sp-cms-storage"

[[d1_databases]]
binding = "DB"
database_name = "sp_cms"
database_id = "your-database-id-here"