name: Deploy Portal

on:
  push:
    branches: [main]
    paths: ['packages/sp-cms.portal/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Portal
        run: pnpm --filter sp-cms.portal build
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}

      - name: Create Cloudflare Pages project
        run: npx wrangler pages project create sp-cms-portal --production-branch=main || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        
      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy ./packages/sp-cms.portal/dist --project-name=sp-cms-portal
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
